version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/examples/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Enable version updates for Node.js
  - package-ecosystem: "npm"
    directory: "/examples/nodejs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "nodejs"
    commit-message:
      prefix: "npm"
      include: "scope"

  # Enable version updates for Go
  - package-ecosystem: "gomod"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "go"
      include: "scope"

  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/examples/java"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "maven"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "action"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/examples/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/examples/nodejs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "cbwinslow"
    labels:
      - "dependencies"
      - "docker"