# Pre-commit configuration for Template2
# Install with: pip install pre-commit && pre-commit install

repos:
  # Python code formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: black (python)
        files: ^examples/python/
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: ^examples/python/
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8 (python)
        files: ^examples/python/
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: mypy (python)
        files: ^examples/python/
        additional_dependencies: [types-all]

  # JavaScript/TypeScript formatting and linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier (js/ts)
        files: ^examples/nodejs/
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        name: eslint (js/ts)
        files: ^examples/nodejs/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.54.0
          - "@typescript-eslint/eslint-plugin@6.12.0"
          - "@typescript-eslint/parser@6.12.0"

  # Go formatting and linting
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        name: go fmt
        files: ^examples/go/
      - id: go-imports
        name: go imports
        files: ^examples/go/
      - id: go-vet
        name: go vet
        files: ^examples/go/
      - id: go-mod-tidy
        name: go mod tidy
        files: ^examples/go/
      - id: golangci-lint
        name: golangci-lint
        files: ^examples/go/

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-yaml
        name: check yaml
      - id: check-json
        name: check json
      - id: check-toml
        name: check toml
      - id: check-xml
        name: check xml
      - id: check-merge-conflict
        name: check for merge conflicts
      - id: check-added-large-files
        name: check for large files
        args: ['--maxkb=1000']
      - id: check-case-conflict
        name: check for case conflicts
      - id: check-executables-have-shebangs
        name: check that executables have shebangs
      - id: fix-byte-order-marker
        name: fix byte order marker
      - id: mixed-line-ending
        name: mixed line ending

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit (python security)
        files: ^examples/python/
        exclude: ^examples/python/tests/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: ['--baseline', '.secrets.baseline']

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: hadolint (dockerfile)
        files: Dockerfile

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        name: markdownlint
        args: [--fix]

  # Commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        name: conventional commit
        stages: [commit-msg]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier (yaml)
        files: \.(yaml|yml)$
        types: [yaml]

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: shellcheck
        files: \.(sh|bash)$

# Configuration for specific hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false