name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Check PR
        id: check-pr
        run: |
          # Check if this is a minor or patch update
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          
          # Determine if we should auto-merge based on the title
          if [[ "${{ github.event.pull_request.title }}" =~ ^(pip|npm|go|maven|action)\(deps\): ]]; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
          else
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Enable auto-merge
        if: steps.check-pr.outputs.auto_merge == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: steps.check-pr.outputs.auto_merge == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 Auto-merging this dependency update after CI passes."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}