name: Dependency Review

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-dependencies-licenses: GPL-3.0, BSD-3-Clause, MIT, ISC, Apache-2.0
          deny-licenses: AGPL-1.0, AGPL-3.0
          comment-summary-in-pr: always